name: blinky

services:
  redis:
    image: redis:7-alpine
    env_file:
      - ../.env
    command:
      - sh
      - -c
      - redis-server --requirepass $$REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: blinky
      POSTGRES_PASSWORD: blinky
      POSTGRES_DB: blinky
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blinky"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  redis-data:
  postgres_data:
